# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VollumeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_story', models.IntegerField(validators=django.core.validators.MinValueValidator(1))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('para', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stories.Para')),
            ],
        ),
        migrations.RenameModel(
            old_name='Story',
            new_name='Vollume',
        ),
        migrations.RemoveField(
            model_name='storystructure',
            name='para',
        ),
        migrations.RemoveField(
            model_name='storystructure',
            name='story',
        ),
        migrations.DeleteModel(
            name='StoryStructure',
        ),
        migrations.AddField(
            model_name='vollumestructure',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='stories.Vollume'),
        ),
    ]
