# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20160411_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='vollume',
            name='title',
            field=models.CharField(default='The best Vollume ever', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vollumestructure',
            name='order_in_story',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
