# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 21:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vollumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VollumeChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(500)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vollumes.VollumeChunk')),
                ('vollume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='vollumes.Vollume')),
            ],
        ),
        migrations.RemoveField(
            model_name='vollumestructure',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vollumestructure',
            name='para',
        ),
        migrations.RemoveField(
            model_name='vollumestructure',
            name='vollume',
        ),
        migrations.DeleteModel(
            name='Para',
        ),
        migrations.DeleteModel(
            name='VollumeStructure',
        ),
    ]
