# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vollumes', '0002_auto_20160519_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vollume',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vollumechunk',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vollumes.VollumeChunk'),
        ),
    ]
