# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vollumes', '0003_auto_20160607_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vollumechunk',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vollumes.VollumeChunk'),
        ),
    ]
