# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vollumes', '0004_auto_20160823_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vollumechunk',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
